// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpQndgg77VByl3DatJveAaVvIVY-yrMRU',
    appId: '1:302667582499:web:31aad61665d78bba03b596',
    messagingSenderId: '302667582499',
    projectId: 'spotify0101-clone',
    authDomain: 'spotify0101-clone.firebaseapp.com',
    storageBucket: 'spotify0101-clone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD-O65bKRJ_GQh2dwrWX9NY2xJGuZAGJE',
    appId: '1:302667582499:android:dea870ea4fff808203b596',
    messagingSenderId: '302667582499',
    projectId: 'spotify0101-clone',
    storageBucket: 'spotify0101-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5V2YpCjwZPMypgB2aPXmdyHmIUwQ-Y4w',
    appId: '1:302667582499:ios:7d0d2671ec50516c03b596',
    messagingSenderId: '302667582499',
    projectId: 'spotify0101-clone',
    storageBucket: 'spotify0101-clone.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5V2YpCjwZPMypgB2aPXmdyHmIUwQ-Y4w',
    appId: '1:302667582499:ios:7d0d2671ec50516c03b596',
    messagingSenderId: '302667582499',
    projectId: 'spotify0101-clone',
    storageBucket: 'spotify0101-clone.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );
}
